CREATE TABLE lang(
    three char(3) PRIMARY KEY,
    two char(2) UNIQUE,
    english varchar(20) NOT NULL
);

CREATE TABLE wikidata(
    id varchar(10) PRIMARY KEY,
    is_author bool NOT NULL,
    commons varchar(60) UNIQUE
);

CREATE TABLE wikipedia(
    id varchar(10) REFERENCES wikidata(id),
    site_lang char(3) REFERENCES lang(three),
    lang_pedia char(2) REFERENCES lang(two),
    slug_pedia varchar(60),
    PRIMARY KEY(id, site_lang)
);

INSERT INTO lang VALUES
('eng', 'en', 'english'),
('fra', 'fr', 'french'),
('deu', 'de', 'german'),
('ita', 'it', 'italian'),
('rus', 'ru', 'russian'),
('spa', 'es', 'spanish'),
('lat', 'la', 'latin'),
('grc', NULL, 'ancient greek');

CREATE TABLE author(
    slug varchar(20) PRIMARY KEY,
    page bool NOT NULL,
    lang char(3) REFERENCES lang(three) NOT NULL,
    birth integer,
    death integer,
    wikidata varchar(10) UNIQUE,
    onlinebooks varchar(60) UNIQUE
);

CREATE TABLE name(
    author varchar(20) REFERENCES author(slug),
    lang char(3) REFERENCES lang(three),
    first_part varchar(30),
    main_part varchar(20) NOT NULL,
    last_part varchar(20),
    PRIMARY KEY(author, lang)
);

CREATE TABLE work(
    slug varchar(40) PRIMARY KEY,
    page bool NOT NULL,
    dubious bool NOT NULL,
    wikidata varchar(10) UNIQUE
);

CREATE TABLE title(
    work_slug varchar(40) REFERENCES work(slug),
    lang char(3) REFERENCES lang(three),
    first_part varchar(60),
    main_part varchar(70) NOT NULL,
    last_part varchar(560),
    PRIMARY KEY(work_slug, lang)
);

CREATE TABLE attribution(
    author_slug varchar(20) REFERENCES author(slug),
    work_slug varchar(40) REFERENCES work(slug),
    PRIMARY KEY(author_slug, work_slug)
);

CREATE TABLE edition(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    work_slug varchar(40) REFERENCES work(slug),
    year integer,
    important bool NOT NULL,
    lang char(3) REFERENCES lang(three) NOT NULL,
    translator varchar(20) REFERENCES author(slug),
    description varchar(240) NOT NULL
);

CREATE TABLE quality(
    quality varchar(20) PRIMARY KEY
);

INSERT INTO quality VALUES
('scan'),
('raw'),
('format');

CREATE TABLE website(
    site varchar(20) PRIMARY KEY,
    domain varchar(120) NOT NULL,
    url varchar(120)
);

CREATE TABLE source(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    site varchar(20) references website(site),
    url varchar(120) UNIQUE,
    lang char(3) REFERENCES lang(three),
    quality varchar(6) references quality(quality),
    download bool NOT NULL,
    description varchar(240) NOT NULL
);

CREATE TABLE edition_source(
    edition integer REFERENCES edition(id),
    source integer REFERENCES source(id),
    PRIMARY KEY(edition, source)
);

